### ISSUE TITLE
Error creating decoder manifest when calling vehiclemodelhandler.py  

### ISSUE THREAD

**Issue by jamboubou** [aws-samples/cdk-aws-iotfleetwise#20]
Hello,

When calling vehiclemodelhandler.py lambda it fails with "[ERROR] ValidationException: An error occurred (ValidationException) when calling the CreateDecoderManifest operation: 1 validation error detected: Value null at 'networkInterfaces.1.member.canInterface.name' failed to satisfy constraint: Member must not be null"

Checking the latest boto3 1.24.85 doc [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iotfleetwise.html#IoTFleetWise.Client.create_decoder_manifest) seems that structure of networkInterfaces.canInterface has changed and is expecting a property 'name' instead of 'canInterfaceName' as defined in this cdk construct in vehiclemodel.ts [here](https://github.com/aws-samples/cdk-aws-iotfleetwise/blob/main/src/vehiclemodel.ts) line 29

**Comment by fsalamida** [comment]
Hi, you are right. Service API has been changed. I have just merged the pull request that fix it ([v0.2.12](https://github.com/aws-samples/cdk-aws-iotfleetwise/releases/tag/v0.2.12))
